### PR TITLE
Team data - adding 2021 small logos

### PR DESCRIPTION
**Pull request by alexnoob**
hey, I suck at Github. It's my first pull request so I hope I didn't fuck up

It's still a WIP, could you confirm the team data.json update is fine for you? I've added small logos for 2021 teams + a few other changes here and there (I guess you'll notice). I'm sill working on the file, but I'd just want to confirm if everything is fine for you this way

### CODE REVIEW

**Comment by domini7** [comment]
Everything looks good. You can keep updating your fork, and it'll update this pull-request. Let me know when you're done if you're still going.

**Comment by alexnoob** [comment]
Thanks a lot, it may take a few more days. You might have noticed I also updated a few existing logos (adding white border for better visibility in dark background), and updated a few teams colors (better contrast for players numbers, also to better mimic jerseys instead of only logos colors - I'm thinking of the gray background/pink border used for 90's Spurs which wasn't used at all on jerseys. I've replaced colors for black background/grey border)

**Comment by alexnoob** [comment]
Dumbmatter made his annual post on /r/nba https://www.reddit.com/r/nba/comments/pamwyr/i_made_basketball_gm_a_free_basketball_management/

I think I'm pretty much done on the update. There might be some improvements possible here and there, but couldn't find much more to do. I'd suggest to make an update post on /r/basketballgm. I'll let you handle it if you're OK? (so you get that sweet +12 karma points)

**Comment by domini7** [comment]
thanks a lot, ill make the post in a bit

**Pull request merged**
